export const GET_COMPTES = "GET_COMPTES";
export const GET_RATES = "GET_DEVISE";
export const SELECT_COMPTE_DEBITE = "SELECT_COMPTE_DEBITE";
export const SELECT_COMPTE_CREDITE = "SELECT_COMPTE_CREDITE";
export const FETCHING_DATA = "FETCHING_DATA";
export const SELECT_DATE_EXECUTION = "SELECT_DATE_EXECUTION";
export const SET_INITIAL_FORM_VALUES = "SET_INITIAL_FORM_VALUES";
export const SET_CURRENT_VIREMENT = "SET_CURRENT_VIREMENT";
export const SET_VIREMENTS = "SET_VIREMENTS";
export const DELETE_VIREMENT = "DELETE_VIREMENT";
export const CONFIRMER_VIREMENT = "CONFIRMER_VIREMENT";
export const DATA_NOT_FOUND = "DATA_NOT_FOUND";



 // Beneficiare Actions
export const GET_BANQUES = "GET_BANQUES";
export const GET_COUNTRIES = "GET_COUNTRIES";

// Stepper Actions
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";

// dialog
export const OPEN_DIALOG = "OPEN_DIALOG";
